- hosts: all
  become: yes
  tasks:

  - name: Disable SWAP
    shell: |
      swapoff -a

  - name: prerequistes
    shell: |
      cat > /etc/modules-load.d/containerd.conf <<EOF
          overlay
          br_netfilter
          EOF
      modprobe overlay
      modprobe br_netfilter
      cat > /etc/sysctl.d/99-kubernetes-cri.conf <<EOF
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          EOF
      sysctl --system

  - name: Install containerd
    shell: |
      dnf install -y  yum-utils device-mapper-persistent-data lvm2
      dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

  - name: install d
    dnf:
      name: containerd.io
      state: present

  - name: Configure containerd(restart & enable)
    shell: |
      mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.toml
      systemctl restart containerd
      systemctl enable containerd

  - name: Install Kubernetes (kubeadm, kubelet and kubectl)
    shell: |
      cat <<EOF > /etc/yum.repos.d/kubernetes.repo
       [kubernetes]
       name=Kubernetes
       baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       enabled=1
       gpgcheck=1
       repo_gpgcheck=1
       gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
       EOF
      dnf install -y kubeadm-1.17.0 kubelet-1.17.0 kubectl-1.17.0
      systemctl enable kubelet
      echo 'KUBELET_EXTRA_ARGS="--fail-swap-on=false"' > /etc/sysconfig/kubelet
      systemctl start kubelet
